"""ventas: comprobante, detalle y los lotes de los que salió

El módulo existía como esbozo y no como modelo: `venta.py` heredaba de
`unittest.mock.Base` —la clase de la librería de tests, no el `Base`
declarativo— y declaraba `__table_name__` en lugar de `__tablename__`, así que
nunca fue una tabla. `venta_detalle.py` estaba vacío.

`venta_lote` es nueva y no estaba en el esbozo: una línea puede consumir varios
lotes, y sin dejar escrito de cuál salió cada unidad no se puede devolver el
stock a donde estaba al anular la venta, ni saber a quién se le vendió un lote
que hay que retirar.

Revision ID: 21cf3b5f3426
Revises: e5c93a17d8b4
Create Date: 2026-08-18 18:20:41.336641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cf3b5f3426'
down_revision: Union[str, None] = 'e5c93a17d8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_comprobante',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('descripcion', sa.String(length=25), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tipo_comprobante'))
    )
    op.create_table('ventas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('almacen_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('serie_comprobante', sa.String(length=4), nullable=False),
    sa.Column('numero_comprobante', sa.String(length=8), nullable=False),
    sa.Column('tipo_comprobante_id', sa.UUID(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('ruc_cliente', sa.String(length=11), nullable=True),
    sa.Column('estado_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], name=op.f('fk_ventas_almacen_id_almacenes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], name=op.f('fk_ventas_estado_id_estados'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_comprobante_id'], ['tipo_comprobante.id'], name=op.f('fk_ventas_tipo_comprobante_id_tipo_comprobante'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas')),
    sa.UniqueConstraint('tipo_comprobante_id', 'serie_comprobante', 'numero_comprobante', name='uq_venta_comprobante')
    )
    op.create_index(op.f('ix_ventas_almacen_id'), 'ventas', ['almacen_id'], unique=False)
    op.create_index(op.f('ix_ventas_estado_id'), 'ventas', ['estado_id'], unique=False)
    op.create_index(op.f('ix_ventas_tipo_comprobante_id'), 'ventas', ['tipo_comprobante_id'], unique=False)
    op.create_table('venta_detalle',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venta_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name=op.f('ck_venta_detalle_chk_venta_detalle_cantidad_positiva')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('fk_venta_detalle_producto_id_productos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name=op.f('fk_venta_detalle_venta_id_ventas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_detalle')),
    sa.UniqueConstraint('venta_id', 'producto_id', name='uq_venta_detalle_producto')
    )
    op.create_index(op.f('ix_venta_detalle_producto_id'), 'venta_detalle', ['producto_id'], unique=False)
    op.create_index(op.f('ix_venta_detalle_venta_id'), 'venta_detalle', ['venta_id'], unique=False)
    op.create_table('venta_lote',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('venta_detalle_id', sa.UUID(), nullable=False),
    sa.Column('producto_lote_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['producto_lote_id'], ['producto_lote.id'], name=op.f('fk_venta_lote_producto_lote_id_producto_lote'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venta_detalle_id'], ['venta_detalle.id'], name=op.f('fk_venta_lote_venta_detalle_id_venta_detalle'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venta_lote'))
    )
    op.create_index(op.f('ix_venta_lote_producto_lote_id'), 'venta_lote', ['producto_lote_id'], unique=False)
    op.create_index(op.f('ix_venta_lote_venta_detalle_id'), 'venta_lote', ['venta_detalle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venta_lote_venta_detalle_id'), table_name='venta_lote')
    op.drop_index(op.f('ix_venta_lote_producto_lote_id'), table_name='venta_lote')
    op.drop_table('venta_lote')
    op.drop_index(op.f('ix_venta_detalle_venta_id'), table_name='venta_detalle')
    op.drop_index(op.f('ix_venta_detalle_producto_id'), table_name='venta_detalle')
    op.drop_table('venta_detalle')
    op.drop_index(op.f('ix_ventas_tipo_comprobante_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_estado_id'), table_name='ventas')
    op.drop_index(op.f('ix_ventas_almacen_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_table('tipo_comprobante')
    # ### end Alembic commands ###
