"""unicidad de la equivalencia por unidad

Revision ID: 295e2b236ed7
Revises: 88c59f5a133c
Create Date: 2026-08-12 13:21:26.060608

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "295e2b236ed7"
down_revision: Union[str, None] = "88c59f5a133c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_tabla_equivalencia_unidad", "tabla_equivalencia", ["unidad_medida_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_tabla_equivalencia_unidad", "tabla_equivalencia", type_="unique"
    )
    # ### end Alembic commands ###
