"""movimientos y producto_lote

Revision ID: 3b346b56409a
Revises: c3e7a94d15b8
Create Date: 2026-08-12 10:44:27.135869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b346b56409a"
down_revision: Union[str, None] = "c3e7a94d15b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estados",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("descripcion", sa.String(length=30), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estados")),
    )
    op.create_table(
        "requerimientos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("almacen_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("estado_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["almacen_id"],
            ["almacenes.id"],
            name=op.f("fk_requerimientos_almacen_id_almacenes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
            name=op.f("fk_requerimientos_estado_id_estados"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requerimientos")),
    )
    op.create_index(
        op.f("ix_requerimientos_almacen_id"),
        "requerimientos",
        ["almacen_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requerimientos_estado_id"),
        "requerimientos",
        ["estado_id"],
        unique=False,
    )
    op.create_table(
        "pedidos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("requerimiento_id", sa.UUID(), nullable=False),
        sa.Column("estado_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
            name=op.f("fk_pedidos_estado_id_estados"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requerimiento_id"],
            ["requerimientos.id"],
            name=op.f("fk_pedidos_requerimiento_id_requerimientos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedidos")),
    )
    op.create_index(
        op.f("ix_pedidos_estado_id"), "pedidos", ["estado_id"], unique=False
    )
    op.create_index(
        op.f("ix_pedidos_requerimiento_id"),
        "pedidos",
        ["requerimiento_id"],
        unique=False,
    )
    op.create_table(
        "requerimiento_detalle",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("requerimiento_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_requerimiento_detalle_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requerimiento_id"],
            ["requerimientos.id"],
            name=op.f("fk_requerimiento_detalle_requerimiento_id_requerimientos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_requerimiento_detalle_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requerimiento_detalle")),
        sa.UniqueConstraint(
            "requerimiento_id", "producto_id", name="uq_requerimiento_detalle_producto"
        ),
    )
    op.create_index(
        op.f("ix_requerimiento_detalle_producto_id"),
        "requerimiento_detalle",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requerimiento_detalle_requerimiento_id"),
        "requerimiento_detalle",
        ["requerimiento_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requerimiento_detalle_unidad_medida_id"),
        "requerimiento_detalle",
        ["unidad_medida_id"],
        unique=False,
    )
    op.create_table(
        "cotizaciones",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("proveedor_id", sa.UUID(), nullable=False),
        sa.Column("monto_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("tiempo_atencion", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("estado_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
            name=op.f("fk_cotizaciones_estado_id_estados"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_cotizaciones_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["empresas.id"],
            name=op.f("fk_cotizaciones_proveedor_id_empresas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cotizaciones")),
    )
    op.create_index(
        op.f("ix_cotizaciones_estado_id"), "cotizaciones", ["estado_id"], unique=False
    )
    op.create_index(
        op.f("ix_cotizaciones_pedido_id"), "cotizaciones", ["pedido_id"], unique=False
    )
    op.create_index(
        op.f("ix_cotizaciones_proveedor_id"),
        "cotizaciones",
        ["proveedor_id"],
        unique=False,
    )
    op.create_table(
        "pedido_detalle",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("pedido_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["pedido_id"],
            ["pedidos.id"],
            name=op.f("fk_pedido_detalle_pedido_id_pedidos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_pedido_detalle_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_pedido_detalle_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pedido_detalle")),
        sa.UniqueConstraint(
            "pedido_id", "producto_id", name="uq_pedido_detalle_producto"
        ),
    )
    op.create_index(
        op.f("ix_pedido_detalle_pedido_id"),
        "pedido_detalle",
        ["pedido_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedido_detalle_producto_id"),
        "pedido_detalle",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pedido_detalle_unidad_medida_id"),
        "pedido_detalle",
        ["unidad_medida_id"],
        unique=False,
    )
    op.create_table(
        "cotizacion_detalle",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("cotizacion_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("monto_producto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cotizacion_id"],
            ["cotizaciones.id"],
            name=op.f("fk_cotizacion_detalle_cotizacion_id_cotizaciones"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_cotizacion_detalle_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_cotizacion_detalle_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cotizacion_detalle")),
        sa.UniqueConstraint(
            "cotizacion_id", "producto_id", name="uq_cotizacion_detalle_producto"
        ),
    )
    op.create_index(
        op.f("ix_cotizacion_detalle_cotizacion_id"),
        "cotizacion_detalle",
        ["cotizacion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_detalle_producto_id"),
        "cotizacion_detalle",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cotizacion_detalle_unidad_medida_id"),
        "cotizacion_detalle",
        ["unidad_medida_id"],
        unique=False,
    )
    op.create_table(
        "orden_compra",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("cotizacion_id", sa.UUID(), nullable=False),
        sa.Column("proveedor_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("estado_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cotizacion_id"],
            ["cotizaciones.id"],
            name=op.f("fk_orden_compra_cotizacion_id_cotizaciones"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
            name=op.f("fk_orden_compra_estado_id_estados"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["empresas.id"],
            name=op.f("fk_orden_compra_proveedor_id_empresas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orden_compra")),
    )
    op.create_index(
        op.f("ix_orden_compra_cotizacion_id"),
        "orden_compra",
        ["cotizacion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orden_compra_estado_id"), "orden_compra", ["estado_id"], unique=False
    )
    op.create_index(
        op.f("ix_orden_compra_proveedor_id"),
        "orden_compra",
        ["proveedor_id"],
        unique=False,
    )
    op.create_table(
        "guia_remision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("orden_compra_id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("estado_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["estado_id"],
            ["estados.id"],
            name=op.f("fk_guia_remision_estado_id_estados"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["orden_compra_id"],
            ["orden_compra.id"],
            name=op.f("fk_guia_remision_orden_compra_id_orden_compra"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guia_remision")),
    )
    op.create_index(
        op.f("ix_guia_remision_estado_id"), "guia_remision", ["estado_id"], unique=False
    )
    op.create_index(
        op.f("ix_guia_remision_orden_compra_id"),
        "guia_remision",
        ["orden_compra_id"],
        unique=False,
    )
    op.create_table(
        "orden_compra_detalle",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("orden_compra_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["orden_compra_id"],
            ["orden_compra.id"],
            name=op.f("fk_orden_compra_detalle_orden_compra_id_orden_compra"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_orden_compra_detalle_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_orden_compra_detalle_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orden_compra_detalle")),
        sa.UniqueConstraint(
            "orden_compra_id", "producto_id", name="uq_orden_compra_detalle_producto"
        ),
    )
    op.create_index(
        op.f("ix_orden_compra_detalle_orden_compra_id"),
        "orden_compra_detalle",
        ["orden_compra_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orden_compra_detalle_producto_id"),
        "orden_compra_detalle",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orden_compra_detalle_unidad_medida_id"),
        "orden_compra_detalle",
        ["unidad_medida_id"],
        unique=False,
    )
    op.create_table(
        "producto_lote",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("guia_remision_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("fecha_ingreso", sa.Date(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("codigo_lote", sa.String(length=30), nullable=False),
        sa.Column("fecha_vencimiento", sa.Date(), nullable=True),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "estado IN ('disponible','agotado','inmovilizado')",
            name=op.f("ck_producto_lote_chk_producto_lote_estado"),
        ),
        sa.ForeignKeyConstraint(
            ["guia_remision_id"],
            ["guia_remision.id"],
            name=op.f("fk_producto_lote_guia_remision_id_guia_remision"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_producto_lote_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_producto_lote_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_producto_lote")),
        sa.UniqueConstraint(
            "producto_id", "codigo_lote", name="uq_producto_lote_codigo"
        ),
    )
    op.create_index(
        op.f("ix_producto_lote_guia_remision_id"),
        "producto_lote",
        ["guia_remision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_producto_lote_producto_id"),
        "producto_lote",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_producto_lote_unidad_medida_id"),
        "producto_lote",
        ["unidad_medida_id"],
        unique=False,
    )
    op.create_index(op.f("ix_markets_sede_id"), "markets", ["sede_id"], unique=False)
    op.create_index(op.f("ix_sedes_zona_id"), "sedes", ["zona_id"], unique=False)
    op.create_index(
        op.f("ix_sub_categorias_categoria_id"),
        "sub_categorias",
        ["categoria_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_familias_familia_id"), "sub_familias", ["familia_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sub_familias_familia_id"), table_name="sub_familias")
    op.drop_index(op.f("ix_sub_categorias_categoria_id"), table_name="sub_categorias")
    op.drop_index(op.f("ix_sedes_zona_id"), table_name="sedes")
    op.drop_index(op.f("ix_markets_sede_id"), table_name="markets")
    op.drop_index(op.f("ix_producto_lote_unidad_medida_id"), table_name="producto_lote")
    op.drop_index(op.f("ix_producto_lote_producto_id"), table_name="producto_lote")
    op.drop_index(op.f("ix_producto_lote_guia_remision_id"), table_name="producto_lote")
    op.drop_table("producto_lote")
    op.drop_index(
        op.f("ix_orden_compra_detalle_unidad_medida_id"),
        table_name="orden_compra_detalle",
    )
    op.drop_index(
        op.f("ix_orden_compra_detalle_producto_id"), table_name="orden_compra_detalle"
    )
    op.drop_index(
        op.f("ix_orden_compra_detalle_orden_compra_id"),
        table_name="orden_compra_detalle",
    )
    op.drop_table("orden_compra_detalle")
    op.drop_index(op.f("ix_guia_remision_orden_compra_id"), table_name="guia_remision")
    op.drop_index(op.f("ix_guia_remision_estado_id"), table_name="guia_remision")
    op.drop_table("guia_remision")
    op.drop_index(op.f("ix_orden_compra_proveedor_id"), table_name="orden_compra")
    op.drop_index(op.f("ix_orden_compra_estado_id"), table_name="orden_compra")
    op.drop_index(op.f("ix_orden_compra_cotizacion_id"), table_name="orden_compra")
    op.drop_table("orden_compra")
    op.drop_index(
        op.f("ix_cotizacion_detalle_unidad_medida_id"), table_name="cotizacion_detalle"
    )
    op.drop_index(
        op.f("ix_cotizacion_detalle_producto_id"), table_name="cotizacion_detalle"
    )
    op.drop_index(
        op.f("ix_cotizacion_detalle_cotizacion_id"), table_name="cotizacion_detalle"
    )
    op.drop_table("cotizacion_detalle")
    op.drop_index(
        op.f("ix_pedido_detalle_unidad_medida_id"), table_name="pedido_detalle"
    )
    op.drop_index(op.f("ix_pedido_detalle_producto_id"), table_name="pedido_detalle")
    op.drop_index(op.f("ix_pedido_detalle_pedido_id"), table_name="pedido_detalle")
    op.drop_table("pedido_detalle")
    op.drop_index(op.f("ix_cotizaciones_proveedor_id"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_pedido_id"), table_name="cotizaciones")
    op.drop_index(op.f("ix_cotizaciones_estado_id"), table_name="cotizaciones")
    op.drop_table("cotizaciones")
    op.drop_index(
        op.f("ix_requerimiento_detalle_unidad_medida_id"),
        table_name="requerimiento_detalle",
    )
    op.drop_index(
        op.f("ix_requerimiento_detalle_requerimiento_id"),
        table_name="requerimiento_detalle",
    )
    op.drop_index(
        op.f("ix_requerimiento_detalle_producto_id"), table_name="requerimiento_detalle"
    )
    op.drop_table("requerimiento_detalle")
    op.drop_index(op.f("ix_pedidos_requerimiento_id"), table_name="pedidos")
    op.drop_index(op.f("ix_pedidos_estado_id"), table_name="pedidos")
    op.drop_table("pedidos")
    op.drop_index(op.f("ix_requerimientos_estado_id"), table_name="requerimientos")
    op.drop_index(op.f("ix_requerimientos_almacen_id"), table_name="requerimientos")
    op.drop_table("requerimientos")
    op.drop_table("estados")
    # ### end Alembic commands ###
