"""markets bancos y proveedores

Revision ID: 3c65ed377fab
Revises: d3f80a1c9e21
Create Date: 2026-08-07 16:15:42.989251

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c65ed377fab"
down_revision: str | None = "d3f80a1c9e21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bancos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("razon_social", sa.String(length=100), nullable=False),
        sa.Column("ruc", sa.String(length=11), nullable=False),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=15), nullable=True),
        sa.Column("codigo", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bancos")),
    )
    op.create_table(
        "empresas",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("razon_social", sa.String(length=100), nullable=False),
        sa.Column("ruc", sa.String(length=11), nullable=True),
        sa.Column("direccion", sa.String(length=255), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("es_proveedor", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_empresas")),
    )
    op.create_table(
        "tipo_cuenta",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("descripcion", sa.String(length=50), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tipo_cuenta")),
    )
    op.create_table(
        "zonas",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zonas")),
    )
    op.create_table(
        "cuentas",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("numero_cuenta", sa.String(length=20), nullable=False),
        sa.Column("banco_id", sa.UUID(), nullable=False),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("tipo_cuenta_id", sa.UUID(), nullable=False),
        sa.Column("moneda", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["banco_id"],
            ["bancos.id"],
            name=op.f("fk_cuentas_banco_id_bancos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
            name=op.f("fk_cuentas_empresa_id_empresas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tipo_cuenta_id"],
            ["tipo_cuenta.id"],
            name=op.f("fk_cuentas_tipo_cuenta_id_tipo_cuenta"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuentas")),
    )
    op.create_table(
        "sedes",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("zona_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["zona_id"],
            ["zonas.id"],
            name=op.f("fk_sedes_zona_id_zonas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sedes")),
    )
    op.create_table(
        "markets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("sede_id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["sede_id"],
            ["sedes.id"],
            name=op.f("fk_markets_sede_id_sedes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
    )
    op.create_table(
        "proveedor_productos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("tiempo_atencion", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
            name=op.f("fk_proveedor_productos_empresa_id_empresas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_proveedor_productos_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proveedor_productos")),
        sa.UniqueConstraint("empresa_id", "producto_id", name="uq_proveedor_producto"),
    )
    op.create_index(
        op.f("ix_proveedor_productos_empresa_id"),
        "proveedor_productos",
        ["empresa_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proveedor_productos_producto_id"),
        "proveedor_productos",
        ["producto_id"],
        unique=False,
    )
    op.drop_index(
        "uq_categorias_codigo",
        table_name="categorias",
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index("uq_categorias_sub_familia_nombre", table_name="categorias")
    op.drop_index(
        "uq_familias_codigo",
        table_name="familias",
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index("uq_familias_nombre", table_name="familias")
    op.drop_index(
        "uq_presentaciones_codigo",
        table_name="presentaciones",
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index("uq_presentaciones_descripcion", table_name="presentaciones")
    op.add_column(
        "productos", sa.Column("codigo_sunat", sa.String(length=8), nullable=True)
    )
    op.drop_index(
        "uq_productos_codigo_barras",
        table_name="productos",
        postgresql_where="(codigo_barras IS NOT NULL)",
    )
    op.drop_index("uq_productos_sku", table_name="productos")
    op.drop_index("ix_productos_sku", table_name="productos")
    op.create_index(op.f("ix_productos_sku"), "productos", ["sku"], unique=True)
    op.drop_index("uq_sub_categorias_categoria_nombre", table_name="sub_categorias")
    op.drop_index(
        "uq_sub_categorias_codigo",
        table_name="sub_categorias",
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index(
        "uq_sub_familias_codigo",
        table_name="sub_familias",
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index("uq_sub_familias_familia_nombre", table_name="sub_familias")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_sub_familias_familia_nombre",
        "sub_familias",
        ["familia_id", sa.text("lower(TRIM(BOTH FROM nombre))")],
        unique=True,
    )
    op.create_index(
        "uq_sub_familias_codigo",
        "sub_familias",
        [sa.text("lower(TRIM(BOTH FROM codigo))")],
        unique=True,
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.create_index(
        "uq_sub_categorias_codigo",
        "sub_categorias",
        [sa.text("lower(TRIM(BOTH FROM codigo))")],
        unique=True,
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.create_index(
        "uq_sub_categorias_categoria_nombre",
        "sub_categorias",
        ["categoria_id", sa.text("lower(TRIM(BOTH FROM nombre))")],
        unique=True,
    )
    op.drop_index(op.f("ix_productos_sku"), table_name="productos")
    op.create_index("ix_productos_sku", "productos", ["sku"], unique=False)
    op.create_index(
        "uq_productos_sku",
        "productos",
        [sa.text("lower(TRIM(BOTH FROM sku))")],
        unique=True,
    )
    op.create_index(
        "uq_productos_codigo_barras",
        "productos",
        [sa.text("lower(TRIM(BOTH FROM codigo_barras))")],
        unique=True,
        postgresql_where="(codigo_barras IS NOT NULL)",
    )
    op.drop_column("productos", "codigo_sunat")
    op.create_index(
        "uq_presentaciones_descripcion",
        "presentaciones",
        [sa.text("lower(TRIM(BOTH FROM descripcion))")],
        unique=True,
    )
    op.create_index(
        "uq_presentaciones_codigo",
        "presentaciones",
        [sa.text("lower(TRIM(BOTH FROM codigo))")],
        unique=True,
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.create_index(
        "uq_familias_nombre",
        "familias",
        [sa.text("lower(TRIM(BOTH FROM nombre))")],
        unique=True,
    )
    op.create_index(
        "uq_familias_codigo",
        "familias",
        [sa.text("lower(TRIM(BOTH FROM codigo))")],
        unique=True,
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.create_index(
        "uq_categorias_sub_familia_nombre",
        "categorias",
        ["sub_familia_id", sa.text("lower(TRIM(BOTH FROM nombre))")],
        unique=True,
    )
    op.create_index(
        "uq_categorias_codigo",
        "categorias",
        [sa.text("lower(TRIM(BOTH FROM codigo))")],
        unique=True,
        postgresql_where="(codigo IS NOT NULL)",
    )
    op.drop_index(
        op.f("ix_proveedor_productos_producto_id"), table_name="proveedor_productos"
    )
    op.drop_index(
        op.f("ix_proveedor_productos_empresa_id"), table_name="proveedor_productos"
    )
    op.drop_table("proveedor_productos")
    op.drop_table("markets")
    op.drop_table("sedes")
    op.drop_table("cuentas")
    op.drop_table("zonas")
    op.drop_table("tipo_cuenta")
    op.drop_table("empresas")
    op.drop_table("bancos")
    # ### end Alembic commands ###
