"""implementando bases de datos de maestro producto y parte de maestro de proveedores

Revision ID: 4f67736b1867
Revises: be87a34f2f15
Create Date: 2026-08-06 16:41:02.732313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f67736b1867"
down_revision: str | None = "be87a34f2f15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presentaciones",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("descripcion", sa.String(length=150), nullable=False),
        sa.Column("codigo", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presentaciones")),
    )
    op.create_table(
        "productos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("tipo_producto", sa.String(length=20), nullable=False),
        sa.Column("categoria_id", sa.UUID(), nullable=False),
        sa.Column("sub_categoria_id", sa.UUID(), nullable=True),
        sa.Column("familia_id", sa.UUID(), nullable=False),
        sa.Column("sub_familia_id", sa.UUID(), nullable=False),
        sa.Column("presentacion_id", sa.UUID(), nullable=False),
        sa.Column("descripcion_corta", sa.String(length=32), nullable=False),
        sa.Column("descripcion_legal", sa.String(length=100), nullable=False),
        sa.Column("descripcion_compra", sa.String(length=100), nullable=False),
        sa.Column("descripcion_web", sa.String(length=100), nullable=False),
        sa.Column("sku", sa.String(length=15), nullable=False),
        sa.Column("codigo_barras", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
            name=op.f("fk_productos_categoria_id_categorias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["familia_id"],
            ["familias.id"],
            name=op.f("fk_productos_familia_id_familias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["presentacion_id"],
            ["presentaciones.id"],
            name=op.f("fk_productos_presentacion_id_presentaciones"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sub_categoria_id"],
            ["sub_categorias.id"],
            name=op.f("fk_productos_sub_categoria_id_sub_categorias"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sub_familia_id"],
            ["sub_familias.id"],
            name=op.f("fk_productos_sub_familia_id_sub_familias"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_productos")),
    )
    op.create_index(
        op.f("ix_productos_categoria_id"), "productos", ["categoria_id"], unique=False
    )
    op.create_index(
        op.f("ix_productos_familia_id"), "productos", ["familia_id"], unique=False
    )
    op.create_index(
        op.f("ix_productos_presentacion_id"),
        "productos",
        ["presentacion_id"],
        unique=False,
    )
    op.create_index(op.f("ix_productos_sku"), "productos", ["sku"], unique=True)
    op.create_index(
        op.f("ix_productos_sub_categoria_id"),
        "productos",
        ["sub_categoria_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_productos_sub_familia_id"),
        "productos",
        ["sub_familia_id"],
        unique=False,
    )
    op.create_table(
        "precio_producto",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("precio_compra", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fecha_inicio", sa.Date(), nullable=False),
        sa.Column("fecha_fin", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.CheckConstraint(
            "fecha_fin IS NULL OR fecha_fin >= fecha_inicio",
            name=op.f("ck_precio_producto_fecha_fin_posterior"),
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_precio_producto_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_precio_producto")),
    )
    op.create_index(
        op.f("ix_precio_producto_producto_id"),
        "precio_producto",
        ["producto_id"],
        unique=False,
    )
    op.add_column("categorias", sa.Column("sub_familia_id", sa.UUID(), nullable=False))
    op.add_column(
        "categorias",
        sa.Column("margen_ganancia", sa.Numeric(precision=12, scale=2), nullable=False),
    )
    op.alter_column(
        "categorias",
        "codigo",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "categorias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_categorias_sub_familia_id"),
        "categorias",
        ["sub_familia_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_categorias_sub_familia_id_sub_familias"),
        "categorias",
        "sub_familias",
        ["sub_familia_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.alter_column(
        "familias",
        "codigo",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "familias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sub_categorias",
        "codigo",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "sub_categorias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sub_familias",
        "codigo",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "sub_familias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sub_familias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sub_familias",
        "codigo",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=3),
        existing_nullable=True,
    )
    op.alter_column(
        "sub_categorias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sub_categorias",
        "codigo",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=3),
        existing_nullable=True,
    )
    op.alter_column(
        "familias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "familias",
        "codigo",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=3),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("fk_categorias_sub_familia_id_sub_familias"),
        "categorias",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_categorias_sub_familia_id"), table_name="categorias")
    op.alter_column(
        "categorias",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "categorias",
        "codigo",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=3),
        existing_nullable=True,
    )
    op.drop_column("categorias", "margen_ganancia")
    op.drop_column("categorias", "sub_familia_id")
    op.drop_index(op.f("ix_precio_producto_producto_id"), table_name="precio_producto")
    op.drop_table("precio_producto")
    op.drop_index(op.f("ix_productos_sub_familia_id"), table_name="productos")
    op.drop_index(op.f("ix_productos_sub_categoria_id"), table_name="productos")
    op.drop_index(op.f("ix_productos_sku"), table_name="productos")
    op.drop_index(op.f("ix_productos_presentacion_id"), table_name="productos")
    op.drop_index(op.f("ix_productos_familia_id"), table_name="productos")
    op.drop_index(op.f("ix_productos_categoria_id"), table_name="productos")
    op.drop_table("productos")
    op.drop_table("presentaciones")
    # ### end Alembic commands ###
