"""empresa ubigeo y agentes de retencion

Revision ID: 5d317417c07b
Revises: 3c65ed377fab
Create Date: 2026-08-07 17:08:50.192670

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d317417c07b"
down_revision: str | None = "3c65ed377fab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "empresas", sa.Column("ubigeo_sunat", sa.String(length=6), nullable=False)
    )
    op.add_column(
        "empresas",
        sa.Column(
            "es_ag_retencion",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "empresas",
        sa.Column(
            "es_ag_percepcion",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.alter_column(
        "empresas", "ruc", existing_type=sa.VARCHAR(length=11), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "empresas", "ruc", existing_type=sa.VARCHAR(length=11), nullable=True
    )
    op.drop_column("empresas", "es_ag_percepcion")
    op.drop_column("empresas", "es_ag_retencion")
    op.drop_column("empresas", "ubigeo_sunat")
    # ### end Alembic commands ###
