"""guia remision detalle

Revision ID: 88c59f5a133c
Revises: 4e230a25ac98
Create Date: 2026-08-12 12:08:34.578690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88c59f5a133c"
down_revision: Union[str, None] = "4e230a25ac98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guia_remision_detalle",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("guia_remision_id", sa.UUID(), nullable=False),
        sa.Column("producto_id", sa.UUID(), nullable=False),
        sa.Column("unidad_medida_id", sa.UUID(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["guia_remision_id"],
            ["guia_remision.id"],
            name=op.f("fk_guia_remision_detalle_guia_remision_id_guia_remision"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["productos.id"],
            name=op.f("fk_guia_remision_detalle_producto_id_productos"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unidad_medida_id"],
            ["unidades_medida.id"],
            name=op.f("fk_guia_remision_detalle_unidad_medida_id_unidades_medida"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guia_remision_detalle")),
        sa.UniqueConstraint(
            "guia_remision_id", "producto_id", name="uq_guia_remision_detalle_producto"
        ),
    )
    op.create_index(
        op.f("ix_guia_remision_detalle_guia_remision_id"),
        "guia_remision_detalle",
        ["guia_remision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guia_remision_detalle_producto_id"),
        "guia_remision_detalle",
        ["producto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_guia_remision_detalle_unidad_medida_id"),
        "guia_remision_detalle",
        ["unidad_medida_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_guia_remision_detalle_unidad_medida_id"),
        table_name="guia_remision_detalle",
    )
    op.drop_index(
        op.f("ix_guia_remision_detalle_producto_id"), table_name="guia_remision_detalle"
    )
    op.drop_index(
        op.f("ix_guia_remision_detalle_guia_remision_id"),
        table_name="guia_remision_detalle",
    )
    op.drop_table("guia_remision_detalle")
    # ### end Alembic commands ###
