"""empresa estado

Revision ID: df3b8a0d4e0d
Revises: 5d317417c07b
Create Date: 2026-08-07 17:23:40.518379

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df3b8a0d4e0d'
down_revision: str | None = '5d317417c07b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('estado', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'estado')
    # ### end Alembic commands ###
